---
- hosts: all
  become: yes
  tasks:
  - name: update package & install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify: 
    - restart apache
    when: ansible_os_family == "Debian"
  - name: install httpd
    yum:
      name: httpd
      update_cache: yes
      state: present
    notify: 
    - restart httpd
    when: ansible_os_family == "Redhat"
  - name: Install php packeges debian
    apt:
      name:    
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
    notify: 
    - restart apache
    when: ansible_os_family == "Debian"
  - name: Install php packages for redhat
    yum:
      name: 
      - php
      - php-mysql
    notify: 
    - restart httpd
    when: ansible_os_family == "reddhat"
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"
  - name: restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted
    when: ansible_os_family == "redhat"


