---
- hosts: all
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify: 
    - restart httpd
  - name: Install php packages for redhat
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-mysql
    notify: 
    - restart httpd
  handlers:
  - name: restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted
   